### ISSUE TITLE
Instructions for running locally

### ISSUE THREAD

**Issue by scottyhq** [e-marshall/itslive#11]
In order to run these notebooks on my laptop I had to do a few things:

1. remove prefix from `itslivetools_environment.yml` and install itslivetools from git (`pip install git+https://github.com/e-marshall/itslivetools@ef1012d`) could add a tag to use @v0.0.2 instead of commit hash `ef1012d`)
`mamba env create -f itslivetools_environment.yml --prefix /Users/scott/miniconda3/envs/itslivetools`

2. notebooks have kernel names so `jb build .` fails:
```
Exception occurred:
  File "/Users/scott/miniconda3/envs/itslivetools/lib/python3.10/site-packages/jupyter_client/kernelspec.py", line 294, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-itslivetools-py
```
solution: a global search and replace: 
```
sed -i '' 's/conda-env-itslivetools-py/python3/g' *.ipynb`
sed -i '' 's/conda-env-mynewbook-py/python3/g' *.ipynb
```

**Comment by e-marshall** [comment]
Thanks @scottyhq ! Do you think I should add those instructions for running locally in the readme, or  maybe the `software and data` notebook?

**Comment by dcherian** [comment]
```shell
nbstripout --keep-output --extra-keys="metadata.kernelspec metadata.language_info.version" *.ipynb
```

This should work. It'll keep the output  but strip kernel info.

-----

Many people use [pre-commit](https://pre-commit.com/) to enforce things like this.  Here's the [config](https://github.com/xarray-contrib/xarray-tutorial/blob/main/.pre-commit-config.yaml) for xarray-tutorial. If you set it up, it'll run checks every time you commit. It'll make changes, so you stage the changes, commit again and then it'll succeed and let you type in the commit message. 

It can be annoying but also useful!

**Comment by e-marshall** [comment]
Thanks @dcherian ! I'll check this out. For now removed the kernel info in 8848e0f698393f251bf149b3037be7eac1c8cfbf
