### ISSUE TITLE
Increase Jupyter Book Cell Timeout Limits

### ISSUE THREAD

**Issue by scottyhq** [e-marshall/itslive#13]
The default is 30 seconds https://jupyterbook.org/en/stable/content/execute.html?highlight=timeout#setting-execution-timeout 

So cells that take longer to execute will result in an error `dc_ls = [read_in_s3(x) for x in granule_ls_32645]` in `accessing_s3_data.ipynb`

**Comment by e-marshall** [comment]
Closed by [https://github.com/e-marshall/itslive/commit/7931936c7b3312879d799c9b08a00aac90424eb8](https://github.com/e-marshall/itslive/commit/7931936c7b3312879d799c9b08a00aac90424eb8)
