### ISSUE TITLE
region-scale glacier analysis

### ISSUE THREAD

**Issue by dcherian** [e-marshall/itslive#15]
I can't run it so some of these comments might not work!

1. It'd be good to describe the spatial join more mostly by linking out to other resources.
```
rgi_sub = gpd.sjoin(se_asia_prj, dc_bbox_prj, how='inner')
```

2. You can update the groupby instruction: `grouped_ID.mean(dim=['mid_date','stacked_y_x'])` -> `grouped_ID.mean(dim=...)` This applies the mean across all dimensions of `grouped_ID` and nicely avoids dealing with `stacked_y_x` which is a bit of an implementation detail.

3. A little more high-level discussion at the top would be useful. Mention that we'll be calculating some extra statistics and adding that back to our GeoDataFrame. (I was a little surprised why you were converting the grouped statistics to dataframe, but now it makes sense to me).

3. Looks like pandas has a [nunique](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html) method so perhaps that could be used instead of `len(set(rgi_itslive['RGIId']))`

**Comment by e-marshall** [comment]
Thanks @dcherian ! I'll incorporate these changes

**Comment by e-marshall** [comment]
closed with 8848e0f698393f251bf149b3037be7eac1c8cfbf
