### ISSUE TITLE
Remove accidental or no longer used files

### ISSUE THREAD

**Issue by scottyhq** [e-marshall/itslive#16]
these can be removed and added to .gitignore, possibly others: 
```
_build
awscli-bundle
```

You can scrub those and other files from the git history with effort, but I don't think you need to bother with that for this repository https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-large-files-on-github#removing-files-from-a-repositorys-history

**Comment by e-marshall** [comment]
Thanks @scottyhq ! I'll add to the .gitignore

**Comment by e-marshall** [comment]
think most unused files were removed in a recent commit -- I'll go back and find which
