### ISSUE TITLE
Enable binder links

### ISSUE THREAD

**Issue by scottyhq** [e-marshall/itslive#17]
https://jupyterbook.org/en/stable/interactive/launchbuttons.html is a really nice feature that would be easy to enable for these notebooks that read from S3.

Currently clicking on the rocketship icons when browsing notebooks reads from `requirements.txt` to setup the environment which doesn't have all the packages. I think that file is left over from earlier setup.  

I'll open a pull request for this

**Comment by e-marshall** [comment]
Thanks @scottyhq ! I'll update the `requirements.txt`

**Comment by e-marshall** [comment]
I wasn't quite sure what format/how specific the `requirements.txt` needs to be but I created it with `conda list -e > requirements.txt` in 538d04df043a38c57d96311b235d142f9b4d42ff
