### ISSUE TITLE
add CITATION.cff file

### ISSUE THREAD

**Issue by dcherian** [e-marshall/itslive#20]
Now that you have a DOI, this will make it appear nicely in the Github UI

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files

**Comment by e-marshall** [comment]
Thanks! I'll work on this

**Comment by e-marshall** [comment]
eek, finally closed on https://github.com/e-marshall/itslive/commit/6096d3190442d9ec92ffa0e65ceff1c1b0e0fabf
