### ISSUE TITLE
Use `%xmode minimal`

### ISSUE THREAD

**Issue by dcherian** [e-marshall/itslive#30]
One thing I realized while quickly scrolling through the books is that %xmode minimal is probably nice. The reader just needs to know the error message, not so much the full traceback.

https://ipython.readthedocs.io/en/stable/interactive/magics.html#magic-xmode

**Comment by e-marshall** [comment]
thanks for this suggestion! incorporated on https://github.com/e-marshall/itslive/commit/aedf9122ff8c3f086a796f8f6d8fa115dc8cc7fd
