### ISSUE TITLE
Add community guidelines

### ISSUE THREAD

**Issue by scottyhq** [e-marshall/itslive#31]
(from https://openjournals.readthedocs.io/en/jose/review_checklist.html)

Community guidelines: Are there clear guidelines for third parties wishing to 1) Contribute to the module 2) Report issues or problems with the module 3) Seek support?

Could just add this to the README.md or first page of JupyterBook. Suggest opening an issue for seeking support or reporting issues. and borrow https://github.com/xarray-contrib/xarray-tutorial/blob/main/CONTRIBUTING.md

**Comment by e-marshall** [comment]
Thanks Scott! I created a contributing page and also a discussions page on the repo, do you think I should keep everything as issues instead of including discussions as well? 
Contributing page was added on https://github.com/e-marshall/itslive/commit/56e0f3d0f7564834e597ed693610721458ab164c

**Comment by scottyhq** [comment]
Nice! I think it's a matter of preference and there are pros and cons so totally up to you. On one hand keeping everything in one place is convenient. But I also like the organizational separation of general discussions and usage questions from bugs and technical issues!

**Comment by e-marshall** [comment]
Okay, thanks! sounds good, I'll keep it separate for now until it becomes inconvenient. I'll close this for now
