### ISSUE TITLE
Fix github button link

### ISSUE THREAD

**Issue by dcherian** [e-marshall/itslive#6]
I think this needs to be the github repo url:
https://github.com/e-marshall/mynewbook/blob/998a5c4e9f760b82d4134676473051ff8793e082/_config.yml#L34

for these links to work:
<img width="423" alt="image" src="https://user-images.githubusercontent.com/2448579/175568464-6dc615d5-b1ec-4181-b5a3-66fb8c03565f.png">

**Comment by e-marshall** [comment]
updated, will push fixed version soon, unless there's a better way to make these edits?

**Comment by e-marshall** [comment]
Thanks!

**Comment by e-marshall** [comment]
addressed in https://github.com/e-marshall/itslive/commit/7931936c7b3312879d799c9b08a00aac90424eb8
