### ISSUE TITLE
Reword learning objectives

### ISSUE THREAD

**Issue by dcherian** [e-marshall/itslive#7]
These are great but a little "in the weeds" especially to someone new to the material ("what is groupby? and dask?")

https://github.com/e-marshall/mynewbook/blob/998a5c4e9f760b82d4134676473051ff8793e082/intro.md?plain=1#L14-L20

One idea is to structure these as "high-level science goal" with "tehcnique" underneath"

For e.g.
- Load ITSlive data from Amazon S3 cloud
   Lazily load cloud datasets using xarray, dask, and zarr.

- Convert vector polygons to raster.
   Use geocube...
   
- Construct seasonal averages of glacier velocity
   Use Xarray's groupby...

**Comment by e-marshall** [comment]
Thanks for these suggestions! Incorporated in https://github.com/e-marshall/itslive/commit/7931936c7b3312879d799c9b08a00aac90424eb8, but can keep making changes
